[theme]
base = "light"
primaryColor = "#c53637"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f1216"
font = "sans serif"
borderColor = "#c2c6cc"
showWidgetBorder = true
